/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import JPA.clienteXpromocaoJpaController;
import JPA.clientenovoJpaController;
import JPA.exceptions.NonexistentEntityException;
import JPA.promocaonovoJpaController;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.clienteXpromocao;
import model.clientenovo;
import model.promocaonovo;

/**
 *
 * @author Peterson
 */
public class guiClientenovo extends javax.swing.JFrame {
    
    private clientenovo cliente;
   

    /**
     * Creates new form guiClientenovo
     */
    public guiClientenovo() {
        initComponents();
        desativabotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstclientes = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        optf = new javax.swing.JRadioButton();
        optm = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txttelefone = new javax.swing.JTextField();
        txtendereco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnsalvar1 = new javax.swing.JToggleButton();
        btnalterar = new javax.swing.JToggleButton();
        btnexcluir = new javax.swing.JToggleButton();
        btnbuscar = new javax.swing.JButton();
        btnnovo = new javax.swing.JToggleButton();
        txtdia = new javax.swing.JTextField();
        txtmes = new javax.swing.JTextField();
        txtano = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JPromocao = new javax.swing.JPanel();
        btnincluir = new javax.swing.JToggleButton();
        jLabel21 = new javax.swing.JLabel();
        cboPromocao = new javax.swing.JComboBox();
        btncartaofidelidade = new javax.swing.JToggleButton();
        btnencerrar = new javax.swing.JToggleButton();
        cartaofidelidade = new javax.swing.JPanel();
        btnincluir1 = new javax.swing.JToggleButton();
        jData1 = new com.toedter.calendar.JDateChooser();
        jData2 = new com.toedter.calendar.JDateChooser();
        jData3 = new com.toedter.calendar.JDateChooser();
        jData5 = new com.toedter.calendar.JDateChooser();
        jData4 = new com.toedter.calendar.JDateChooser();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        btnincluir2 = new javax.swing.JToggleButton();
        btnincluir3 = new javax.swing.JToggleButton();
        btnincluir4 = new javax.swing.JToggleButton();
        btnincluir5 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("AR ESSENCE", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Usuário.png"))); // NOI18N
        jLabel1.setText("CADASTRAR CLIENTE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes Cadastrados"));

        lstclientes.setFont(new java.awt.Font("AR CENA", 0, 18)); // NOI18N
        lstclientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstclientesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstclientes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");

        txtnome.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        jLabel3.setText("CPF:");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        jLabel4.setText("Data Nascimento:");

        jLabel5.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        jLabel5.setText("Sexo:");

        optf.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        optf.setText("F");

        optm.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        optm.setText("M");

        jLabel6.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        jLabel6.setText("Telefone:");

        txttelefone.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N

        txtendereco.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        jLabel7.setText("Endereço:");

        txtemail.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        txtemail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel8.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        jLabel8.setText("E-mail:");

        btnsalvar1.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        btnsalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Ok.png"))); // NOI18N
        btnsalvar1.setText("Salvar");
        btnsalvar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsalvar1MouseClicked(evt);
            }
        });
        btnsalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar1ActionPerformed(evt);
            }
        });

        btnalterar.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        btnalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Alterar.png"))); // NOI18N
        btnalterar.setText("Alterar");
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });

        btnexcluir.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        btnexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        btnbuscar.setFont(new java.awt.Font("AR CENA", 0, 18)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Buscar-pequeno.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnnovo.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        btnnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.png"))); // NOI18N
        btnnovo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnnovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnovoMouseClicked(evt);
            }
        });
        btnnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovoActionPerformed(evt);
            }
        });

        txtdia.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        txtdia.setText("DD");
        txtdia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdiaFocusGained(evt);
            }
        });

        txtmes.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        txtmes.setText("MM");
        txtmes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmesFocusGained(evt);
            }
        });

        txtano.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        txtano.setText("AAAA");
        txtano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanoActionPerformed(evt);
            }
        });
        txtano.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtanoFocusGained(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        jLabel9.setText("/");

        jLabel10.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        jLabel10.setText("/");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtemail)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(optf)
                                        .addGap(18, 18, 18)
                                        .addComponent(optm)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel10)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel9)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtano, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtendereco, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnbuscar))
                                    .addComponent(txtnome))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnexcluir)
                        .addGap(57, 57, 57)
                        .addComponent(btnalterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsalvar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(optf)
                    .addComponent(optm)
                    .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnsalvar1)
                        .addComponent(btnalterar)
                        .addComponent(btnexcluir))
                    .addComponent(btnnovo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPromocao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnincluir.setBackground(new java.awt.Color(255, 255, 153));
        btnincluir.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        btnincluir.setText("Incluir");
        btnincluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnincluirMouseClicked(evt);
            }
        });
        btnincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnincluirActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        jLabel21.setText("Promoção (Fidelidade):");

        cboPromocao.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        cboPromocao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPromocaoItemStateChanged(evt);
            }
        });
        cboPromocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPromocaoActionPerformed(evt);
            }
        });

        btncartaofidelidade.setBackground(new java.awt.Color(255, 255, 153));
        btncartaofidelidade.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        btncartaofidelidade.setText("Cartão Fidelidade");
        btncartaofidelidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncartaofidelidadeMouseClicked(evt);
            }
        });
        btncartaofidelidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncartaofidelidadeActionPerformed(evt);
            }
        });

        btnencerrar.setBackground(new java.awt.Color(255, 255, 153));
        btnencerrar.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        btnencerrar.setText("Encerrar Promoção");
        btnencerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnencerrarMouseClicked(evt);
            }
        });
        btnencerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnencerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPromocaoLayout = new javax.swing.GroupLayout(JPromocao);
        JPromocao.setLayout(JPromocaoLayout);
        JPromocaoLayout.setHorizontalGroup(
            JPromocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPromocaoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboPromocao, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnincluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncartaofidelidade)
                .addGap(47, 47, 47)
                .addComponent(btnencerrar)
                .addGap(28, 28, 28))
        );
        JPromocaoLayout.setVerticalGroup(
            JPromocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPromocaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPromocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cboPromocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnincluir)
                    .addComponent(btncartaofidelidade)
                    .addComponent(btnencerrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cartaofidelidade.setBackground(new java.awt.Color(255, 255, 204));
        cartaofidelidade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnincluir1.setBackground(new java.awt.Color(255, 255, 153));
        btnincluir1.setFont(new java.awt.Font("AR ESSENCE", 0, 14)); // NOI18N
        btnincluir1.setForeground(new java.awt.Color(204, 0, 0));
        btnincluir1.setText("Incluir");
        btnincluir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnincluir1MouseClicked(evt);
            }
        });
        btnincluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnincluir1ActionPerformed(evt);
            }
        });

        jData1.setBackground(new java.awt.Color(255, 255, 204));
        jData1.setFont(new java.awt.Font("AR CENA", 0, 18)); // NOI18N

        jData2.setBackground(new java.awt.Color(255, 255, 204));
        jData2.setFont(new java.awt.Font("AR CENA", 0, 18)); // NOI18N

        jData3.setBackground(new java.awt.Color(255, 255, 204));
        jData3.setFont(new java.awt.Font("AR CENA", 0, 18)); // NOI18N

        jData5.setBackground(new java.awt.Color(255, 255, 204));
        jData5.setFont(new java.awt.Font("AR CENA", 0, 18)); // NOI18N

        jData4.setBackground(new java.awt.Color(255, 255, 204));
        jData4.setFont(new java.awt.Font("AR CENA", 0, 18)); // NOI18N

        jLabel28.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        jLabel28.setText("Data 1");

        jLabel29.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        jLabel29.setText("Data 2");

        jLabel30.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        jLabel30.setText("Data 3");

        jLabel31.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        jLabel31.setText("Data 4");

        jLabel32.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        jLabel32.setText("Data 5");

        btnincluir2.setBackground(new java.awt.Color(255, 255, 153));
        btnincluir2.setFont(new java.awt.Font("AR ESSENCE", 0, 14)); // NOI18N
        btnincluir2.setForeground(new java.awt.Color(204, 0, 0));
        btnincluir2.setText("Incluir");
        btnincluir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnincluir2MouseClicked(evt);
            }
        });
        btnincluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnincluir2ActionPerformed(evt);
            }
        });

        btnincluir3.setBackground(new java.awt.Color(255, 255, 153));
        btnincluir3.setFont(new java.awt.Font("AR ESSENCE", 0, 14)); // NOI18N
        btnincluir3.setForeground(new java.awt.Color(204, 0, 0));
        btnincluir3.setText("Incluir");
        btnincluir3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnincluir3MouseClicked(evt);
            }
        });
        btnincluir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnincluir3ActionPerformed(evt);
            }
        });

        btnincluir4.setBackground(new java.awt.Color(255, 255, 153));
        btnincluir4.setFont(new java.awt.Font("AR ESSENCE", 0, 14)); // NOI18N
        btnincluir4.setForeground(new java.awt.Color(204, 0, 0));
        btnincluir4.setText("Incluir");
        btnincluir4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnincluir4MouseClicked(evt);
            }
        });
        btnincluir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnincluir4ActionPerformed(evt);
            }
        });

        btnincluir5.setBackground(new java.awt.Color(255, 255, 153));
        btnincluir5.setFont(new java.awt.Font("AR ESSENCE", 0, 14)); // NOI18N
        btnincluir5.setForeground(new java.awt.Color(204, 0, 0));
        btnincluir5.setText("Incluir");
        btnincluir5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnincluir5MouseClicked(evt);
            }
        });
        btnincluir5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnincluir5ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel27.setFont(new java.awt.Font("AR ESSENCE", 1, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 0, 0));
        jLabel27.setText("C A R T Ã O   D E   F I D E L I D A D E");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel27))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cartaofidelidadeLayout = new javax.swing.GroupLayout(cartaofidelidade);
        cartaofidelidade.setLayout(cartaofidelidadeLayout);
        cartaofidelidadeLayout.setHorizontalGroup(
            cartaofidelidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartaofidelidadeLayout.createSequentialGroup()
                .addGroup(cartaofidelidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartaofidelidadeLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnincluir1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnincluir2)
                        .addGap(163, 163, 163)
                        .addComponent(btnincluir3)
                        .addGap(93, 93, 93))
                    .addGroup(cartaofidelidadeLayout.createSequentialGroup()
                        .addGroup(cartaofidelidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cartaofidelidadeLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel28))
                            .addGroup(cartaofidelidadeLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jData1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(cartaofidelidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cartaofidelidadeLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jData2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addComponent(jData3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))
                            .addGroup(cartaofidelidadeLayout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel30)
                                .addGap(112, 112, 112)))))
                .addGroup(cartaofidelidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jData4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cartaofidelidadeLayout.createSequentialGroup()
                        .addGroup(cartaofidelidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cartaofidelidadeLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btnincluir4))
                            .addGroup(cartaofidelidadeLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel31)))
                        .addGap(39, 39, 39)))
                .addGap(57, 57, 57)
                .addGroup(cartaofidelidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartaofidelidadeLayout.createSequentialGroup()
                        .addComponent(btnincluir5)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartaofidelidadeLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartaofidelidadeLayout.createSequentialGroup()
                        .addComponent(jData5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cartaofidelidadeLayout.setVerticalGroup(
            cartaofidelidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartaofidelidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(cartaofidelidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cartaofidelidadeLayout.createSequentialGroup()
                        .addGroup(cartaofidelidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cartaofidelidadeLayout.createSequentialGroup()
                                .addGroup(cartaofidelidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartaofidelidadeLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(cartaofidelidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cartaofidelidadeLayout.createSequentialGroup()
                                .addComponent(jData3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnincluir3))
                            .addGroup(cartaofidelidadeLayout.createSequentialGroup()
                                .addGroup(cartaofidelidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jData1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                    .addComponent(jData2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(cartaofidelidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnincluir2)
                                    .addComponent(btnincluir1)))))
                    .addGroup(cartaofidelidadeLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jData5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnincluir5))
                    .addGroup(cartaofidelidadeLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jData4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnincluir4))
                    .addComponent(jLabel31))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cartaofidelidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(JPromocao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPromocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartaofidelidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstclientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstclientesValueChanged

        clientenovo c = (clientenovo)lstclientes.getSelectedValue();

        txtnome.setText(c.getNome());
        txtCpf.setText(c.getId());
        txtdia.setText(String.valueOf(c.getDia()));
        txtmes.setText(String.valueOf(c.getMes()));
        txtano.setText(String.valueOf(c.getAno()));
        txtemail.setText(c.getEmail());
        txttelefone.setText(c.getTelefone());
        txtendereco.setText(c.getEndereco());

        if (c.getSexo().equals("Masculino")){
            optm.setSelected(true);
        } else {
            optf.setSelected(true);
        }

    }//GEN-LAST:event_lstclientesValueChanged

    private void desativabotoes(){
        //DESATIVAR A OPÇÃO DE PROMOÇÃO
        jLabel21.setEnabled(false);
        cboPromocao.setEnabled(false);
        btnincluir.setEnabled(false);
        btncartaofidelidade.setEnabled(false);
        btnencerrar.setEnabled(false);
        
         //DESATIVAR CARTÃO FIDELIDADE
        cartaofidelidade.setBackground(Color.gray);
        jLabel27.setEnabled(false);
        jLabel28.setEnabled(false);
        jData1.setEnabled(false);
        btnincluir1.setEnabled(false);
        jLabel29.setEnabled(false);
        jData2.setEnabled(false);
        btnincluir2.setEnabled(false);
        jLabel30.setEnabled(false);
        jData3.setEnabled(false);
        btnincluir3.setEnabled(false);
        jLabel31.setEnabled(false);
        jData4.setEnabled(false);
        btnincluir4.setEnabled(false);
        jLabel32.setEnabled(false);
        jData5.setEnabled(false);
        btnincluir5.setEnabled(false);
                
    }
    
    private void btnsalvar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalvar1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar1MouseClicked

    private void btnsalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar1ActionPerformed
        
            cliente  = new clientenovo();
            cliente.setNome(txtnome.getText());
            cliente.setId(txtCpf.getText());
            cliente.setDia(Integer.parseInt(txtdia.getText()));
            cliente.setMes(Integer.parseInt(txtmes.getText()));
            cliente.setAno(Integer.parseInt(txtano.getText()));
            //cliente.setData_nasc(txtdatanasc.getCalendar());
            cliente.setEmail(txtemail.getText());
            cliente.setTelefone(txttelefone.getText());
            cliente.setEndereco(txtendereco.getText());
           
            
            if (optf.isSelected()){
                cliente.setSexo("Feminino");
            }else{
                cliente.setSexo("Masculino");
            }
            try {
                new clientenovoJpaController().create(cliente);
            } catch (Exception ex) {
                Logger.getLogger(guiClientenovo.class.getName()).log(Level.SEVERE, null, ex);
            }

            List l = new clientenovoJpaController().findclientenovoEntities();
            lstclientes.setListData(l.toArray());

            JOptionPane.showMessageDialog(null, "CLIENTE CADASTRADO COM SUCESSO!");

            txtnome.setText("");
            txtCpf.setText("");
            txtdia.setText("DD");
            txtmes.setText("MM");
            txtano.setText("AAAA");
            //txtdatanasc.setCalendar(null);
            txtemail.setText("");
            txttelefone.setText("");
            txtendereco.setText("");
            optm.setSelected(false);
            optf.setSelected(false);

            txtCpf.grabFocus();
            
            

            // TODO add your handling code here:
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar1ActionPerformed

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed

         if (cliente==null) return;
        
        cliente.setNome(txtnome.getText());
        cliente.setId(txtCpf.getText());
        cliente.setDia(Integer.parseInt(txtdia.getText()));
        cliente.setMes(Integer.parseInt(txtmes.getText()));
        cliente.setAno(Integer.parseInt(txtano.getText()));
        //cliente.setData_nasc(txtdatanasc.getCalendar());
        cliente.setEmail(txtemail.getText());
        cliente.setTelefone(txttelefone.getText());
        cliente.setEndereco(txtendereco.getText());
        if (optf.isSelected()){
            cliente.setSexo("Feminino");
        }else{
            cliente.setSexo("Masculino");
        }

        try{
            new clientenovoJpaController().edit(cliente);
         } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "Cliente Não Cadastrado");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage() + " Procure o Administrador do Sistema");
        }

        JOptionPane.showMessageDialog(null,"Dados Alterados");

        txtnome.setText("");
        txtCpf.setText("");
        txtdia.setText("DD");
        txtmes.setText("MM");
        txtano.setText("AAAA");
        //txtdatanasc.setCalendar(null);
        txtemail.setText("");
        txttelefone.setText("");
        txtendereco.setText("");
        optm.setSelected(false);
        optf.setSelected(false);

        txtCpf.grabFocus();

    }//GEN-LAST:event_btnalterarActionPerformed

    @SuppressWarnings("empty-statement")
    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed

        int resposta;
        
        cliente = (clientenovo) lstclientes.getSelectedValue();

        try {
            resposta = JOptionPane.showConfirmDialog(null, "DESEJA EXCLUIR ESTE CLIENTE?", "Deseja apagar?", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION){
                new clientenovoJpaController().destroy(cliente.getId());
                JOptionPane.showMessageDialog(null, "CLIENTE EXCLUIDO!");
            } else {
                //código que cancela a exclusão
                 txtnome.setText("");
                 txtCpf.setText("");
                 txtdia.setText("DD");
                 txtmes.setText("MM");
                 txtano.setText("AAAA");                 
//txtdatanasc.setCalendar(null);
                 txtemail.setText("");
                 txttelefone.setText("");
                 txtendereco.setText("");
                 optm.setSelected(false);
                 optf.setSelected(false);
                 txtCpf.grabFocus();
            }
        } catch (NonexistentEntityException ex) {
            
        }
           
    
        
       /* 
        try{
            new clientenovoJpaController().destroy(cliente.getId());
        }  catch (NonexistentEntityException ex){

        }

        JOptionPane.YES_NO_CANCEL_OPTION;
        JOptionPane.showMessageDialog(null, "CLIENTE EXCLUIDO!");
*/
        txtnome.setText("");
        txtCpf.setText("");
        txtdia.setText("DD");
        txtmes.setText("MM");
        txtano.setText("AAAA");
        //txtdatanasc.setCalendar(null);
        txtemail.setText("");
        txttelefone.setText("");
        txtendereco.setText("");
        optm.setSelected(false);
        optf.setSelected(false);
        txtCpf.grabFocus();
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        
        cboPromocao.removeAllItems();
        List l1 = new promocaonovoJpaController().findpromocaonovoEntities();

        for (int i = 0; i < l1.size(); i++) {
            promocaonovo p = (promocaonovo) l1.get(i);
            cboPromocao.addItem(p);
        }
        
      try{
          cliente = new clientenovoJpaController().findclientenovo(txtCpf.getText());
      } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "CLIENTE NÃO CADASTRADO");
          return;
      }
        
         

        txtnome.setText(cliente.getNome());
        txtCpf.setText(cliente.getId());
        txtdia.setText(String.valueOf(cliente.getDia()));
        txtmes.setText(String.valueOf(cliente.getMes()));
        txtano.setText(String.valueOf(cliente.getAno()));
        //txtdatanasc.setCalendar(cliente.getData_nasc());
        txtemail.setText(cliente.getEmail());
        txttelefone.setText(cliente.getTelefone());
        txtendereco.setText(cliente.getEndereco());
        
        cboPromocao.setSelectedItem(cliente.getPromocao());
        jData1.setDate(cliente.getData01());
        jData2.setDate(cliente.getData02());
        jData3.setDate(cliente.getData03());
        jData4.setDate(cliente.getData04());
        jData5.setDate(cliente.getData05());
        
        //cboMedico.setSelectedItem(inter.getMedico());
        if (cliente.getSexo().equals("Masculino")){
            optm.setSelected(true);
        } else {
            optf.setSelected(true);
        }
        
        //ATIVAR BOTÕES DA PROMOÇAO
        jLabel21.setEnabled(true);
        cboPromocao.setEnabled(true);
        btnincluir.setEnabled(true);
        btncartaofidelidade.setEnabled(true);

    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnnovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnovoMouseClicked

        txtnome.setText("");
        txtCpf.setText("");
        txtdia.setText("");
        txtmes.setText("");
        txtano.setText("");
        //txtdatanasc.setCalendar(null);
        txtemail.setText("");
        txttelefone.setText("");
        txtendereco.setText("");
        optm.setSelected(false);
        optf.setSelected(false);
        txtCpf.grabFocus();
        
        desativabotoes();
    }//GEN-LAST:event_btnnovoMouseClicked

    private void btnnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovoActionPerformed

    }//GEN-LAST:event_btnnovoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        List l = new clientenovoJpaController().findclientenovoEntities();
        lstclientes.setListData(l.toArray());
        
        /*cboPromocao.removeAllItems();
        List l1 = new promocaonovoJpaController().findpromocaonovoEntities();

        for (int i = 0; i < l1.size(); i++) {
            promocaonovo p = (promocaonovo) l1.get(i);
            cboPromocao.addItem(p);
        }*/
        
              
        //DESATIVAR O CARTÃO DE FIDELIDADE
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void txtanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanoActionPerformed

    private void txtdiaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdiaFocusGained

        txtdia.selectAll();// TODO add your handling code here:
    }//GEN-LAST:event_txtdiaFocusGained

    private void txtmesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmesFocusGained

        txtmes.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmesFocusGained

    private void txtanoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtanoFocusGained

        txtano.selectAll();// TODO add your handling code here:
    }//GEN-LAST:event_txtanoFocusGained

    private void cboPromocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPromocaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPromocaoActionPerformed

    private void cboPromocaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPromocaoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPromocaoItemStateChanged

    private void btnincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnincluirActionPerformed

        if (cliente==null) return;
        
        cliente.setPromocao((promocaonovo) cboPromocao.getSelectedItem());
       
        try{
            new clientenovoJpaController().edit(cliente);
         } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "Cliente Não Cadastrado");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage() + " Procure o Administrador do Sistema");
        }

        JOptionPane.showMessageDialog(null,"PROMOÇÃO INCLUÍDA COM SUCESSO!");
         
             
// TODO add your handling code here:
    }//GEN-LAST:event_btnincluirActionPerformed

    private void btnincluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnincluirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnincluirMouseClicked

    private void btncartaofidelidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncartaofidelidadeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btncartaofidelidadeMouseClicked

    private void btncartaofidelidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncartaofidelidadeActionPerformed

        //ATIVAR CARTÃO FIDELIDADE
        cartaofidelidade.setBackground(Color.yellow);
        jLabel27.setEnabled(true);
        jLabel28.setEnabled(true);
        jData1.setEnabled(true);
        btnincluir1.setEnabled(true);
        jLabel29.setEnabled(true);
        jData2.setEnabled(true);
        btnincluir2.setEnabled(true);
        jLabel30.setEnabled(true);
        jData3.setEnabled(true);
        btnincluir3.setEnabled(true);
        jLabel31.setEnabled(true);
        jData4.setEnabled(true);
        btnincluir4.setEnabled(true);
        jLabel32.setEnabled(true);
        jData5.setEnabled(true);
        btnincluir5.setEnabled(true);        
// TODO add your handling code here:
    }//GEN-LAST:event_btncartaofidelidadeActionPerformed

    private void btnencerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnencerrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnencerrarMouseClicked

    private void btnencerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnencerrarActionPerformed
        
        if (cliente==null) return;
        
        clienteXpromocao cp = new clienteXpromocao();
        
        int resposta;
        
        resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente encerrar?","ENCERRAR A PROMOÇÃO", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION){
            cp.setCliente(cliente);
            cp.setData01(jData1.getDate());
            cp.setData02(jData2.getDate());
            cp.setData03(jData3.getDate());
            cp.setData04(jData4.getDate());
            cp.setData05(jData5.getDate());
            cp.setPromocao((promocaonovo) cboPromocao.getSelectedItem());
            
            new clienteXpromocaoJpaController().create(cp);
            JOptionPane.showMessageDialog(null, "PROMOÇÃO ENCERRADA COM SUCESSO!\n CADASTRE UMA NOVA PROMOÇÃO!");
        } else {
            
        }
       
       
       cboPromocao.setActionCommand("");
       jData1.setDate(null);
       jData2.setDate(null);
       jData3.setDate(null);
       jData4.setDate(null);
       jData5.setDate(null);
       
       try{
           new clientenovoJpaController().edit(cliente);
         } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "Cliente Não Cadastrado");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage() + " Procure o Administrador do Sistema");
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnencerrarActionPerformed

    private void btnincluir5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnincluir5ActionPerformed

        if (cliente==null) return;

        cliente.setData05(jData5.getDate());
        //cliente.setData_nasc(txtdatanasc.getCalendar());

        try{
            new clientenovoJpaController().edit(cliente);
        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "Cliente Não Cadastrado");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage() + " Procure o Administrador do Sistema");
        }

        JOptionPane.showMessageDialog(null,"DATA 05 INCLUÍDA COM SUCESSO!");
       // cboPromocao.setName(cliente.getPromocao().getNome());
        btnencerrar.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnincluir5ActionPerformed

    private void btnincluir5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnincluir5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnincluir5MouseClicked

    private void btnincluir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnincluir4ActionPerformed
        if (cliente==null) return;

        cliente.setData04(jData4.getDate());
        //cliente.setData_nasc(txtdatanasc.getCalendar());

        try{
            new clientenovoJpaController().edit(cliente);
        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "Cliente Não Cadastrado");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage() + " Procure o Administrador do Sistema");
        }

        JOptionPane.showMessageDialog(null,"DATA 04 INCLUÍDA COM SUCESSO!");
    }//GEN-LAST:event_btnincluir4ActionPerformed

    private void btnincluir4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnincluir4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnincluir4MouseClicked

    private void btnincluir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnincluir3ActionPerformed

        if (cliente==null) return;

        cliente.setData03(jData3.getDate());
        //cliente.setData_nasc(txtdatanasc.getCalendar());

        try{
            new clientenovoJpaController().edit(cliente);
        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "Cliente Não Cadastrado");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage() + " Procure o Administrador do Sistema");
        }

        JOptionPane.showMessageDialog(null,"DATA 03 INCLUÍDA COM SUCESSO!");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnincluir3ActionPerformed

    private void btnincluir3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnincluir3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnincluir3MouseClicked

    private void btnincluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnincluir2ActionPerformed

        if (cliente==null) return;

        cliente.setData02(jData2.getDate());
        //cliente.setData_nasc(txtdatanasc.getCalendar());

        try{
            new clientenovoJpaController().edit(cliente);
        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "Cliente Não Cadastrado");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage() + " Procure o Administrador do Sistema");
        }

        JOptionPane.showMessageDialog(null,"DATA 02 INCLUÍDA COM SUCESSO!");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnincluir2ActionPerformed

    private void btnincluir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnincluir2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnincluir2MouseClicked

    private void btnincluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnincluir1ActionPerformed

        if (cliente==null) return;

        cliente.setData01(jData1.getDate());
        //cliente.setData_nasc(txtdatanasc.getCalendar());

        try{
            new clientenovoJpaController().edit(cliente);
        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "Cliente Não Cadastrado");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage() + " Procure o Administrador do Sistema");
        }

        JOptionPane.showMessageDialog(null,"DATA 01 INCLUÍDA COM SUCESSO!");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnincluir1ActionPerformed

    private void btnincluir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnincluir1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnincluir1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiClientenovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiClientenovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiClientenovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiClientenovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiClientenovo().setVisible(true);
               
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPromocao;
    private javax.swing.JToggleButton btnalterar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JToggleButton btncartaofidelidade;
    private javax.swing.JToggleButton btnencerrar;
    private javax.swing.JToggleButton btnexcluir;
    private javax.swing.JToggleButton btnincluir;
    private javax.swing.JToggleButton btnincluir1;
    private javax.swing.JToggleButton btnincluir2;
    private javax.swing.JToggleButton btnincluir3;
    private javax.swing.JToggleButton btnincluir4;
    private javax.swing.JToggleButton btnincluir5;
    private javax.swing.JToggleButton btnnovo;
    private javax.swing.JToggleButton btnsalvar1;
    private javax.swing.JPanel cartaofidelidade;
    private javax.swing.JComboBox cboPromocao;
    private javax.swing.Box.Filler filler1;
    private com.toedter.calendar.JDateChooser jData1;
    private com.toedter.calendar.JDateChooser jData2;
    private com.toedter.calendar.JDateChooser jData3;
    private com.toedter.calendar.JDateChooser jData4;
    private com.toedter.calendar.JDateChooser jData5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstclientes;
    private javax.swing.JRadioButton optf;
    private javax.swing.JRadioButton optm;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtano;
    private javax.swing.JTextField txtdia;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtmes;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
