/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Relatórios.JDBC.abrirRelatorioCliente;

/**
 *
 * @author Peterson
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menucadastros = new javax.swing.JMenu();
        cadastrarfuncao = new javax.swing.JMenuItem();
        cadastrarservico = new javax.swing.JMenuItem();
        cadastrarprofissional = new javax.swing.JMenuItem();
        cadastrarcliente = new javax.swing.JMenuItem();
        cadastrarcliente1 = new javax.swing.JMenuItem();
        cadastrarcliente2 = new javax.swing.JMenuItem();
        cadastrarcliente3 = new javax.swing.JMenuItem();
        menuatendimento = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuAgendamento = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MenuAgendar = new javax.swing.JMenuItem();
        menurelatorioclientes = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        cadastrarfuncao1 = new javax.swing.JMenuItem();
        cadastrarfuncao2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo.png"))); // NOI18N

        menucadastros.setText("     CADASTROS     |");
        menucadastros.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N

        cadastrarfuncao.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        cadastrarfuncao.setText("Cadastrar Função");
        cadastrarfuncao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarfuncaoMouseClicked(evt);
            }
        });
        cadastrarfuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarfuncaoActionPerformed(evt);
            }
        });
        menucadastros.add(cadastrarfuncao);

        cadastrarservico.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        cadastrarservico.setText("Cadastrar Serviço");
        cadastrarservico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarservicoMouseClicked(evt);
            }
        });
        cadastrarservico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarservicoActionPerformed(evt);
            }
        });
        menucadastros.add(cadastrarservico);

        cadastrarprofissional.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        cadastrarprofissional.setText("Cadastrar Profissional");
        cadastrarprofissional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarprofissionalMouseClicked(evt);
            }
        });
        cadastrarprofissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarprofissionalActionPerformed(evt);
            }
        });
        menucadastros.add(cadastrarprofissional);

        cadastrarcliente.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        cadastrarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Clientes.png"))); // NOI18N
        cadastrarcliente.setText("Cadastrar Cliente");
        cadastrarcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarclienteMouseClicked(evt);
            }
        });
        cadastrarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarclienteActionPerformed(evt);
            }
        });
        menucadastros.add(cadastrarcliente);

        cadastrarcliente1.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        cadastrarcliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fornecedor.png"))); // NOI18N
        cadastrarcliente1.setText("Cadastrar Fornecedor");
        cadastrarcliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarcliente1MouseClicked(evt);
            }
        });
        cadastrarcliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarcliente1ActionPerformed(evt);
            }
        });
        menucadastros.add(cadastrarcliente1);

        cadastrarcliente2.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        cadastrarcliente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Produto.png"))); // NOI18N
        cadastrarcliente2.setText("Cadastrar Produto");
        cadastrarcliente2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarcliente2MouseClicked(evt);
            }
        });
        cadastrarcliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarcliente2ActionPerformed(evt);
            }
        });
        menucadastros.add(cadastrarcliente2);

        cadastrarcliente3.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        cadastrarcliente3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/equipamentos.png"))); // NOI18N
        cadastrarcliente3.setText("Cadastrar Equipamento");
        cadastrarcliente3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarcliente3MouseClicked(evt);
            }
        });
        cadastrarcliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarcliente3ActionPerformed(evt);
            }
        });
        menucadastros.add(cadastrarcliente3);

        jMenuBar1.add(menucadastros);

        menuatendimento.setText("     ATENDIMENTO     |");
        menuatendimento.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        menuatendimento.add(jSeparator1);

        jMenuBar1.add(menuatendimento);

        menuAgendamento.setText("     AGENDAMENTO     |");
        menuAgendamento.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        menuAgendamento.add(jSeparator2);
        menuAgendamento.add(jSeparator3);

        MenuAgendar.setFont(new java.awt.Font("AR CENA", 0, 24)); // NOI18N
        MenuAgendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/agendar - pe.png"))); // NOI18N
        MenuAgendar.setText("Agendar Cliente");
        MenuAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAgendarActionPerformed(evt);
            }
        });
        menuAgendamento.add(MenuAgendar);

        jMenuBar1.add(menuAgendamento);

        menurelatorioclientes.setText("     RELATÓRIOS     ");
        menurelatorioclientes.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        menurelatorioclientes.add(jSeparator5);
        menurelatorioclientes.add(jSeparator6);

        cadastrarfuncao1.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        cadastrarfuncao1.setText("Clientes Cadastrados");
        cadastrarfuncao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarfuncao1MouseClicked(evt);
            }
        });
        cadastrarfuncao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarfuncao1ActionPerformed(evt);
            }
        });
        menurelatorioclientes.add(cadastrarfuncao1);

        cadastrarfuncao2.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        cadastrarfuncao2.setText("Controle de Estoque");
        cadastrarfuncao2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarfuncao2MouseClicked(evt);
            }
        });
        cadastrarfuncao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarfuncao2ActionPerformed(evt);
            }
        });
        menurelatorioclientes.add(cadastrarfuncao2);

        jMenuBar1.add(menurelatorioclientes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(98, 98, 98))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarfuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarfuncaoActionPerformed
        new guiFuncao().setVisible(true);
        
                // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarfuncaoActionPerformed

    private void cadastrarfuncaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarfuncaoMouseClicked
     
    }//GEN-LAST:event_cadastrarfuncaoMouseClicked

    private void cadastrarservicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarservicoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarservicoMouseClicked

    private void cadastrarservicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarservicoActionPerformed

        new guiServico().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarservicoActionPerformed

    private void cadastrarprofissionalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarprofissionalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarprofissionalMouseClicked

    private void cadastrarprofissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarprofissionalActionPerformed

        new guiProfissional().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarprofissionalActionPerformed

    private void cadastrarclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarclienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarclienteMouseClicked

    private void cadastrarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarclienteActionPerformed

        new guiClientenovo().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarclienteActionPerformed

    private void MenuAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAgendarActionPerformed

        new guiAgendamento().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuAgendarActionPerformed

    private void cadastrarcliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarcliente1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarcliente1MouseClicked

    private void cadastrarcliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarcliente1ActionPerformed
        new guiFornecedor().setVisible(true);
    }//GEN-LAST:event_cadastrarcliente1ActionPerformed

    private void cadastrarcliente2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarcliente2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarcliente2MouseClicked

    private void cadastrarcliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarcliente2ActionPerformed
        new guiProduto().setVisible(true);
    }//GEN-LAST:event_cadastrarcliente2ActionPerformed

    private void cadastrarcliente3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarcliente3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarcliente3MouseClicked

    private void cadastrarcliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarcliente3ActionPerformed
        new guiEquipamento().setVisible(true);
    }//GEN-LAST:event_cadastrarcliente3ActionPerformed

    private void cadastrarfuncao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarfuncao1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarfuncao1MouseClicked

    private void cadastrarfuncao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarfuncao1ActionPerformed

        new abrirRelatorioCliente().abrirRelatorioClientes();
       
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarfuncao1ActionPerformed

    private void cadastrarfuncao2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarfuncao2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarfuncao2MouseClicked

    private void cadastrarfuncao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarfuncao2ActionPerformed
        new guiControleEstoque().setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarfuncao2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAgendar;
    private javax.swing.JMenuItem cadastrarcliente;
    private javax.swing.JMenuItem cadastrarcliente1;
    private javax.swing.JMenuItem cadastrarcliente2;
    private javax.swing.JMenuItem cadastrarcliente3;
    private javax.swing.JMenuItem cadastrarfuncao;
    private javax.swing.JMenuItem cadastrarfuncao1;
    private javax.swing.JMenuItem cadastrarfuncao2;
    private javax.swing.JMenuItem cadastrarprofissional;
    private javax.swing.JMenuItem cadastrarservico;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenu menuAgendamento;
    private javax.swing.JMenu menuatendimento;
    private javax.swing.JMenu menucadastros;
    private javax.swing.JMenu menurelatorioclientes;
    // End of variables declaration//GEN-END:variables
}
